services:
  mysql:
    image: mysql:8
    container_name: bikeshare-mysql
    environment:
      MYSQL_DATABASE: bike_share_db
      MYSQL_USER: bikeshare
      MYSQL_PASSWORD: bikeshare
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pbikeshare"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  mysql_data: